# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
