# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0002_auto_20180102_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(),
        ),
    ]
